# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9561f383344e18b47d9cd8355907ad5ab69283737ab93f867b236df0702377fe24d1a68f9cfe22edc4882d1c959ee51577b51ad958cefeefef2dcd2b6a56b50c

test:
  secret_key_base: fc3327514462bfcb9ceabb55db83c433387aa79abb0025c88911953c7d5b554553565bc1029c1b5d8aacaf381e8f8cb00a7df44b9a6f581145d2877d4563546f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
